# Generated by Django 3.2.2 on 2021-05-16 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brand', '0002_auto_20210508_1254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MediaCollection', '0001_initial'),
        ('Product', '0004_product_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndorsementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('InProgress', 'InProgress'), ('PendingDocumentVerification', 'PendingDocumentVerification'), ('PendingIdentityVerification', 'PendingIdentityVerification'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collectionId', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MediaCollection.mediacollection')),
                ('judgedBy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('endorsementdId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('terms', models.TextField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertisementCollections', models.OneToOneField(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MediaCollection.mediacollection')),
                ('brand', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Brand.brand')),
                ('commodities', models.ManyToManyField(related_name='endorsements', to='Product.Commodity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
