# Generated by Django 3.2.2 on 2021-05-22 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Endorsement', '0002_rename_collectionid_endorsementrequest_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrequest',
            name='endorsement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Endorsement.endorsement'),
        ),
    ]
