# Generated by Django 3.2.2 on 2021-05-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaCollection', '0001_initial'),
        ('Brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='advertisementCollections',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_advertisement', to='MediaCollection.mediacollection'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logoCollections',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_logo', to='MediaCollection.mediacollection'),
        ),
    ]
