# Generated by Django 3.2.2 on 2021-05-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_commodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='commodity',
        ),
    ]
