# Generated by Django 3.2.2 on 2021-05-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_commodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='customizationType',
        ),
    ]
