# Generated by Django 3.2.2 on 2021-05-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_commodity_customizationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='customizationType',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodity_customization', to='Product.customizationtype'),
        ),
    ]
