# Generated by Django 3.2.2 on 2021-05-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_commodity_customizationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='commodity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodity_dimensions', to='Product.commodity'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_dimensions', to='Product.product'),
        ),
    ]
