# Generated by Django 3.2.2 on 2021-05-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_leaderrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderRequest',
        ),
    ]
