# Generated by Django 3.2.2 on 2021-05-08 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Location', '0001_initial'),
        ('MediaCollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('eventType', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('public', 'public'), ('private', 'private')], max_length=40)),
                ('eventDescription', models.TextField()),
                ('eventPasscode', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('eventUrl', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('maxParticipants', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=6, null=True)),
                ('eventTimeStamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('eventDuration', models.DurationField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, db_column='location', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.physicallocation')),
                ('mediaCollection', models.ForeignKey(db_column='mediaCollection', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MediaCollection.mediacollection')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
