# Generated by Django 3.2.2 on 2021-05-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaCollection', '0001_initial'),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mediaCollection',
            field=models.ForeignKey(blank=True, db_column='mediaCollection', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MediaCollection.mediacollection'),
        ),
    ]
