# Generated by Django 3.2.2 on 2021-05-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_event_mediacollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
