# Generated by Django 3.2.2 on 2021-05-16 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import litap.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0004_product_commodity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MediaCollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('rating', models.CharField(max_length=5)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mediaCollection', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MediaCollection.mediacollection')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('writerUser', models.ForeignKey(on_delete=models.SET(litap.utils.deleted_user), related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
