# Generated by Django 3.2.2 on 2021-06-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_auto_20210509_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
