# Generated by Django 3.2.2 on 2021-05-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='callbacktoken',
            name='Auth_callba_user_id_509c3a_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='kyc',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.kyc'),
        ),
    ]
