# Generated by Django 3.2.2 on 2021-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20210516_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isTribeLeader',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
