# Generated by Django 3.2.2 on 2021-05-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_user_istribeleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isModerator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
