# Generated by Django 3.2.2 on 2021-05-08 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MediaCollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('mediaId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('mediaType', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Image', 'Image'), ('Document', 'Document')], max_length=20)),
                ('value', models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg', 'jpeg', 'pdf'])])),
                ('mediaCollection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='MediaCollection.mediacollection')),
            ],
        ),
    ]
