# Generated by Django 3.2.2 on 2021-05-08 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaCollection', '0001_initial'),
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mediaCollection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='MediaCollection.mediacollection'),
        ),
    ]
