# Generated by Django 3.2.2 on 2021-05-16 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('orderDate', models.DateTimeField()),
                ('deliveryDate', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('orderStatus', models.CharField(choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('RefundInitiated', 'RefundInitiated'), ('RefundComplete', 'RefundComplete')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('orderProductId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('deliveryType', models.CharField(choices=[('Express', 'Express'), ('OneDay', 'OneDay'), ('Priority', 'Priority')], max_length=20)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveryDate', models.DateTimeField()),
                ('orderStatus', models.CharField(choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('RefundInitiated', 'RefundInitiated'), ('RefundComplete', 'RefundComplete')], max_length=20)),
                ('giftReason', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
