# Generated by Django 3.2.2 on 2021-05-16 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0007_auto_20210516_1138'),
        ('Order', '0001_initial'),
        ('Location', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='GiftBioId',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.bio'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.dimension'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='firstLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.physicallocation'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='productObjects', to='Order.order'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderObjects', to='Product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryAddress',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Location.physicallocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderProducts',
            field=models.ManyToManyField(related_name='orders', through='Order.OrderProducts', to='Product.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
