# Generated by Django 3.2.2 on 2021-05-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='firstLocation',
        ),
    ]
