# Generated by Django 3.2.2 on 2021-05-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
        ('Product', '0007_auto_20210516_1138'),
        ('Order', '0005_auto_20210516_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.dimension'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='firstLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.physicallocation'),
        ),
    ]
