# Generated by Django 3.2.2 on 2021-06-02 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20210516_1138'),
        ('Order', '0009_auto_20210602_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='cart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartObjects', to='Order.cart'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartProductObjects', to='Product.product'),
        ),
    ]
