# Generated by Django 3.2.2 on 2021-06-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_auto_20210602_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('RefundInitiated', 'RefundInitiated'), ('RefundComplete', 'RefundComplete')], default='Processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='deliveryDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
