# Generated by Django 3.2.2 on 2021-06-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_auto_20210603_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='orderStatus',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('RefundInitiated', 'RefundInitiated'), ('RefundComplete', 'RefundComplete')], default='Processing', max_length=20),
        ),
    ]
